#!/bin/sh
# Pushes a new version to PyPi.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

script/setup
script/build_frontend

rm -rf dist home_assistant_frontend.egg-info
python3 -m build
python3 -m twine upload dist/*.whl --skip-existing
